spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billing_db
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: disable

  mail:
    host: smtp.gmail.com
    port: 587
    username: lokeshkr189@gmail.com
    password: mrki flmz dgql obcr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud-name: dijuocb4e
  api-key: 393353355664867
  api-secret: wdpw7wvTGTwLYBt1wHGozc1Q9D4



logging:
  level:
    org.springframework.security: DEBUG